// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAly8sqRMZ8wPTebrD3s8Z9VA-uuPPI2Pk',
    appId: '1:878921847381:web:5a9020d4022cd884e7badc',
    messagingSenderId: '878921847381',
    projectId: 'bloodsource-65bdf',
    authDomain: 'bloodsource-65bdf.firebaseapp.com',
    storageBucket: 'bloodsource-65bdf.appspot.com',
    measurementId: 'G-9H7WL0GBTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQM9n0JZhbpAPD8MD9q1Gt2PXO_ATbWH4',
    appId: '1:878921847381:android:b62764bc87cf92ede7badc',
    messagingSenderId: '878921847381',
    projectId: 'bloodsource-65bdf',
    storageBucket: 'bloodsource-65bdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9ICCc1HCx3FZFRr507dpu_IKHHPuiF4',
    appId: '1:878921847381:ios:91ecee0971dfb136e7badc',
    messagingSenderId: '878921847381',
    projectId: 'bloodsource-65bdf',
    storageBucket: 'bloodsource-65bdf.appspot.com',
    androidClientId: '878921847381-cdnoirn9rktk6ap85hk2cqb2f68ljqf4.apps.googleusercontent.com',
    iosClientId: '878921847381-iiqku5klpb927v5ursetnh97icvdvqvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodSource',
  );
}
